mock_frontend:
  extends:
    file: ../common.yml
    service: mock_frontend
  links:
    - mock_backend:backend
mock_backend:
  extends:
    file: ../common.yml
    service: mock_backend
  environment:
  - SPRING_PROFILES_ACTIVE=local
